### PR TITLE
Breadcrumbs inconsistent 

### PR DESCRIPTION
**Pull request by gerzitom**
Solves #6

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@gerzitom Think this PR has broken a few things:

1. Previewing

Previously, draft blog posts didn't show up if NUXT_ENV_BUTTER_PREVIEW=false was set to false in .env, but now they do: https://share.getcloudapp.com/9Zuorvbx, https://share.getcloudapp.com/DOudwXN9

Additionally, draft content on menu and page didn't show if NUXT_ENV_BUTTER_PREVIEW=false was set to false in .env, but now they show up, regardless of the setting: https://share.getcloudapp.com/04uQem7R.

Additionally, I tried out both preview deployments to make sure they seemed okay.

2. Breadcrumbs menu still broken on search page. Additionally, after a search, breadcrumb link to "blog" broken, and blog posts don't repopulate on the "/blog" page, even after navigating away from page and reloading: https://share.getcloudapp.com/ApuX1BE0

3. Search

Not for this PR, but for the one that follows (the trailing slash PR), search appears to be broken: https://share.getcloudapp.com/llu01j4Q. I realize that's not *this* PR but I think it will likely need to be fixed, so I wanted to point it out. "butter" is a known good search term, since it's mentioned several times in the example post.

**Review by ViolanteCodes — COMMENTED** [review]
Several pieces of functionality now broken, see comment: 

https://github.com/ButterCMS/nuxtjs-starter-buttercms/pull/8#issuecomment-1138596071

**Comment by gerzitom** [comment]
@ViolanteCodes seems like the new version of nuxt created this problem with preview mode. It is fixed now.

**Comment by gerzitom** [comment]
@ViolanteCodes search page is fixed, sorry for the trouble, seems like another problem with the new version, sorry I have not checked it.

**Comment by gerzitom** [comment]
Sorry for that, I see now, that I should have wait with this Nuxt update. I will fix it by today.

**Comment by ViolanteCodes** [comment]
@gerzitom No problem, and thank you :)

**Comment by gerzitom** [comment]
@ViolanteCodes it is fixed sorry once again for the problems with updated Nuxt

**Review by ViolanteCodes — APPROVED** [review]
LGTM

**Pull request merged**
